# Generated by Django 3.2.16 on 2022-10-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='cabecalho',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='paragrafo1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='paragrafo2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='rodape',
            field=models.CharField(max_length=255),
        ),
    ]
