# Generated by Django 3.2.16 on 2022-10-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabecalho', '0002_remove_cabecalho_img'),
        ('rodape', '0001_initial'),
        ('paragrafo2', '0001_initial'),
        ('paragrafo1', '0001_initial'),
        ('oficio', '0002_auto_20221014_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='cabecalho',
        ),
        migrations.AddField(
            model_name='oficio',
            name='cabecalho',
            field=models.ManyToManyField(to='cabecalho.Cabecalho'),
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='paragrafo1',
        ),
        migrations.AddField(
            model_name='oficio',
            name='paragrafo1',
            field=models.ManyToManyField(to='paragrafo1.Paragrafo1'),
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='paragrafo2',
        ),
        migrations.AddField(
            model_name='oficio',
            name='paragrafo2',
            field=models.ManyToManyField(to='paragrafo2.Paragrafo2'),
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='rodape',
        ),
        migrations.AddField(
            model_name='oficio',
            name='rodape',
            field=models.ManyToManyField(to='rodape.Rodape'),
        ),
    ]
