# Generated by Django 3.2.16 on 2022-10-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabecalho', '0002_remove_cabecalho_img'),
        ('oficio', '0004_auto_20221014_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='cabecalho',
        ),
        migrations.AddField(
            model_name='oficio',
            name='cabecalho',
            field=models.ManyToManyField(to='cabecalho.Cabecalho'),
        ),
    ]
