# Generated by Django 3.2.16 on 2022-10-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabecalho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabecalho',
            name='img',
        ),
    ]
