# Generated by Django 3.2.16 on 2022-10-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imgright', '0001_initial'),
        ('imgleft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('imgleft', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='imgleft', to='imgleft.imgleft')),
                ('imgright', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='imgrigth', to='imgright.imgright')),
            ],
        ),
    ]
